//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationMng.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Avaliability
    {
        [Required(ErrorMessage = "Please Provide Volunteers First Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VFname { get; set; }

        [Required(ErrorMessage = "Please Provide Volunteers Last Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VLname { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> MM { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> MA { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> ME { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> TM { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> TA { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> TE { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> WM { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> WA { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> WE { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> THM { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> THA { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> THE { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> FM { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> FA { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> FE { get; set; }

        [RegularExpression("Yes|No")]
        public Nullable<bool> All { get; set; }

        [RegularExpression("Yes|No")]
        public virtual Volunteer Volunteer { get; set; }
    }
}
