//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationMng.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Opportunity
    {   [Key]
        [Display(Name = "Opportunity Name")]
        [Required(ErrorMessage = "A Opportunity Name is required", AllowEmptyStrings = false)]
        public string OName { get; set; }
        [Required(ErrorMessage = "A Date is required", AllowEmptyStrings = false)]
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        [Required(ErrorMessage = "A Center is required", AllowEmptyStrings = false)]
        public string Center { get; set; }
    }
}
