//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationMng.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VImage
    {
        [Required(ErrorMessage = "Please Provide Volunteers First Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VFname { get; set; }
        [Required(ErrorMessage = "Please Provide Volunteers First Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VLname { get; set; }
        public byte[] VSSpic { get; set; }
        public byte[] VDLpic { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
