//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrationMng.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Volunteer
    {


        [Required(ErrorMessage = "Please Provide Volunteers First Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VFname { get; set; }


        [Required(ErrorMessage = "Please Provide Volunteers Last Name", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VLname { get; set; }

        [Required(ErrorMessage = "Please Provide a Username", AllowEmptyStrings = false)]
         public string VUsername { get; set; }

        [Required(ErrorMessage = "Please Provide a Password", AllowEmptyStrings = false)]
        public string VPassword { get; set; }

        [Required(ErrorMessage = "Please Provide a Educational Background", AllowEmptyStrings = false)]
        public string VEdu { get; set; }

        [Required(ErrorMessage = "Please Provide a Center you desire to volunteer at", AllowEmptyStrings = false)]
        public string Center { get; set; }

        [Required(ErrorMessage = "Please Provide a Skill", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string VSkills { get; set; }

        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VAddress { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VWorkPhone { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VHomePhone { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VCellPhone { get; set; }

        [Required(ErrorMessage = "Please Provide a Email Address", AllowEmptyStrings = false)]
        [EmailAddress(ErrorMessage = "Please enter a valid Email address")]
        public string VEmail { get; set; }

        [RegularExpression("Yes|No")]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VCurrentLicense { get; set; }

        [RegularExpression("Yes|No")]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VDL { get; set; }

        [RegularExpression("Yes|No")]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string VSS { get; set; }

        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string ECFname { get; set; }

        
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string ECLname { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string ECHomePhone { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string ECWorkPhone { get; set; }


        [Required(ErrorMessage = "Please Provide a Email Address", AllowEmptyStrings = false)]
        [EmailAddress(ErrorMessage = "Please enter a valid Email address")]
        public string ECEmail { get; set; }


        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string ECAddress { get; set; }

        [Required(ErrorMessage = "This a Required Field", AllowEmptyStrings = false)]
        public string Status { get; set; }
    
        public virtual VImage VImage { get; set; }
        public virtual Avaliability Avaliability { get; set; }
    }
}
